---

# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# Prepare servers
- import_playbook: build.yml
# Add monitoring
#- import_playbook: elk.yml

- name: setup forwarders between trusted domains
  hosts: dc
  roles:
    - dnsforwarder

- name: enable TGT delegation for parent-child abuse on the sandbox domain controller - this can fail, while the trust is still building so we retry a few times
  hosts: dc02
  tasks:
    - name: enable TGT delegation
      win_command: netdom.exe trust sandbox.pwnzone.lab /domain:pwnzone.lab /EnableTGTDelegation:Yes
      retries: 2
      delay: 30

- name: enable TGT delegation for parent-child abuse on the pwnzone domain controller - this can fail, while the trust is still building so we retry a few times
  hosts: dc01
  tasks:
    - name: enable TGT delegation
      win_command: netdom.exe trust pwnzone.lab /domain:sandbox.pwnzone.lab /EnableTGTDelegation:Yes
      retries: 2
      delay: 30

- name: enable TGT delegation for parent-child abuse on the sandbox domain controller - this can fail, while the trust is still building so we retry a few times
  hosts: dc01
  tasks:
    - name: enable TGT delegation
      win_command: netdom.exe trust pwnzone.lab /domain:treasureisland.lab /EnableTGTDelegation:Yes
      retries: 2
      delay: 30

- name: enable TGT delegation for parent-child abuse on the pwnzone domain controller - this can fail, while the trust is still building so we retry a few times
  hosts: dc03
  tasks:
    - name: enable TGT delegation
      win_command: netdom.exe trust treasureisland.lab /domain:pwnzone.lab /EnableTGTDelegation:Yes
      retries: 2
      delay: 30

- name: reboot all DCs to apply deleg settings
  hosts: dc
  tasks:
    - name: Reboot
      win_reboot:
    - name: Wait for machines to come back online
      wait_for_connection:
        delay: 10
        timeout: 300

# --------------------------------------------------------------------
# VM ready - start insert specific scenario
# --------------------------------------------------------------------
# Turn server into DC and load active directory data (users/groups/ou)
#- import_playbook: ad.yml
# create main domains, child domain and enroll servers

## AD ----------
#- import_playbook: ad-servers.yml
#- import_playbook: ad-parent_domain.yml
#- import_playbook: ad-child_domain.yml
#- import_playbook: ad-members.yml
# create the trust relationships
#- import_playbook: ad-trusts.yml
# specifics security linked to the scenario are here
#- import_playbook: security.yml
# --------------------------------------------------------------------
# specifics vulns linked to the scenario are here
#- import_playbook: vulnerabilities.yml
#- import_playbook: cred-acl.yml

#- import_playbook: reboot.yml
